## Init

In [7]:
import json
import logging
import operator
import os
import re
import sqlite3
import textwrap
from datetime import date, datetime, time
from functools import partial
from pathlib import Path
from typing import Annotated, Any, Optional, Sequence

import altair as alt
import numpy as np
import polars as pl
import torch
from IPython.utils.capture import capture_output
from polars import col as c
from polars import lit
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from tqdm import tqdm
from transformers import AutoTokenizer

# Configure logging to show timestamp, log level and message
logging.basicConfig(
    format="[%(asctime)s] [%(levelname)s] %(message)s",
    level=logging.INFO,
    datefmt="%Y-%m-%d %H:%M:%S %p",
)
# Add these lines to suppress HTTP request logs
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("requests").setLevel(logging.WARNING)


# set working directory
def set_wdir(wdir) -> tuple[Path, Path]:
    # get working directory
    if isinstance(wdir, str):
        wdir = Path(wdir).expanduser()
    chaoyang_dir = Path("~/chaoyang").expanduser()

    # assert directories exist
    assert wdir.exists()
    assert chaoyang_dir.exists()

    # change working directory
    os.chdir(wdir)

    return wdir, chaoyang_dir


with capture_output():
    # initialize polars
    alt.data_transformers.enable("vegafusion")
    pl.Config.set_tbl_rows(20)  # max number of rows to print

# initialize directories
work_dir, chaoyang_dir = set_wdir("~/chaoyang/projects/Delinquency/delinquency/github/v2")
print(f"WORK DIR: {work_dir}")
print(f"CHAOYANG DIR: {chaoyang_dir}")

WORK DIR: /home/yuzhu/chaoyang/projects/Delinquency/delinquency/github/v2
CHAOYANG DIR: /home/yuzhu/chaoyang

## Data Exploration

In [33]:
# load sample index
samples = pl.read_ipc("data/processed_data/llm_benchmark/samples_min12mo_fixed_2test.feather", memory_map=False)

# load transaction data
transactions = pl.read_ipc("data/raw_data/sample_transaction.feather", memory_map=False)

# how many users? (3178)
print(f"Number of users: {samples['act_idn_sky'].n_unique()}")

# sample size (number of rolling windows)?
print(f"# Obs in Test: {samples.filter(c.split == 'test').height:,}")
print(f"# Obs in Train: {samples.filter(c.split == 'train').height:,}")

# average number of billing cycles for a user?
act_idn_sky = samples["act_idn_sky"].unique().to_list()
avg_n_cycles = (
    transactions.filter(c.act_idn_sky.is_in(act_idn_sky))
    .group_by("act_idn_sky")
    .agg(n_cycles = c.billing_date.n_unique())
    .select(
        avg_n_cycles = c.n_cycles.mean(),
        max_n_cycles = c.n_cycles.max(),
        min_n_cycles = c.n_cycles.min(),
    )
)
print("Summary of billing cycle numbers per user:")
avg_n_cycles


avg_n_txn = (
    transactions.filter(c.act_idn_sky.is_in(act_idn_sky))
    .group_by("act_idn_sky")
    .agg(n_txn=pl.len())
    .select(
        avg_n_txn = c.n_txn.mean(),
        max_n_txn = c.n_txn.max(),
        min_n_txn = c.n_txn.min(),
    )
)
print("Summary of transaction numbers per user:")
avg_n_txn

Number of users: 3178
# Obs in Test: 5,363
# Obs in Train: 17,223
Summary of billing cycle numbers per user:

shape: (1, 3)
┌──────────────┬──────────────┬──────────────┐
│ avg_n_cycles ┆ max_n_cycles ┆ min_n_cycles │
│ ---          ┆ ---          ┆ ---          │
│ f64          ┆ u32          ┆ u32          │
╞══════════════╪══════════════╪══════════════╡
│ 18.106986    ┆ 30           ┆ 12           │
└──────────────┴──────────────┴──────────────┘

Summary of transaction numbers per user:

shape: (1, 3)
┌───────────┬───────────┬───────────┐
│ avg_n_txn ┆ max_n_txn ┆ min_n_txn │
│ ---       ┆ ---       ┆ ---       │
│ f64       ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╡
│ 88.232536 ┆ 1206      ┆ 12        │
└───────────┴───────────┴───────────┘

## Evaluation

### LLM-based

Collect Prediction Results

In [8]:
# function to parse `pred_is_delinquent_raw`
def parse_is_delinquent_raw(s):
    pat = re.compile(r'\{[^{}]*"is_delinquent"\s*:\s*(true|false)[^{}]*\}', re.I | re.S)

    if not isinstance(s, str):
        return None

    m = pat.search(s)
    if not m:
        return None

    try:
        obj = json.loads(m.group(0).replace("True", "true").replace("False", "false"))
        return obj.get("is_delinquent") if isinstance(obj.get("is_delinquent"), bool) else None
    except json.JSONDecodeError:
        return None


# get paths of all preds tables
preds_paths = sorted(list((work_dir / "data/processed_data/llm_benchmark").glob("preds_*.feather")))

# merge all preds tables into one
preds = []
check_cols = ["pred_reasoning_process", "config_max_prompts"]

for i, preds_path in enumerate(preds_paths):
    
    # read preds table
    samples = pl.read_ipc(preds_path, memory_map=False)

    # if has `pred_is_delinquent_raw` column, parse it
    if "pred_is_delinquent_raw" in samples.columns:

        # if `pred_is_delinquent` is not in samples, create it
        if "pred_is_delinquent" not in samples.columns:
            samples = samples.with_columns(pred_is_delinquent=None)

        samples = (
            samples
            # parse `pred_is_delinquent_raw`
            .with_columns(
                pred_is_delinquent_raw_parsed=c.pred_is_delinquent_raw.map_elements(
                    parse_is_delinquent_raw, return_dtype=pl.Boolean
                )
            )
            # update `pred_is_delinquent` with `pred_is_delinquent_raw`
            .with_columns(pred_is_delinquent=pl.coalesce(c.pred_is_delinquent, c.pred_is_delinquent_raw_parsed))
        )

        # drop `pred_is_delinquent_raw` column
        samples = samples.drop("pred_is_delinquent_raw")

        # check if any `pred_is_delinquent_raw` failed to parse
        failures = samples.filter(c.pred_is_delinquent.is_null())
        if failures.height > 0:
            print(f"Warning: {failures.height} rows failed to parse ({preds_path.stem})")

        # drop rows where `pred_is_delinquent` is null
        samples = samples.filter(c.pred_is_delinquent.is_not_null())

    if "pred_a4_output" in samples.columns:
        samples = samples.with_columns(
            pred_is_delinquent=pl.when(c.pred_a4_output.struct.field("is_delinquent").str.to_lowercase()=="true").then(True).otherwise(False),
        )

    # add experiment ID
    exp_id = preds_path.stem
    samples = samples.with_columns(exp_id=lit(exp_id))

    # add benchmark name (e.g., finpt, promptcast, etc.)
    benchmark_name = preds_path.stem.split("_")[1]
    samples = samples.with_columns(benchmark_name=lit(benchmark_name))
    preds.append(samples)

# concat all preds tables
preds = pl.concat(preds, how="diagonal_relaxed")

# if sys_msg is null (e.g., finpt), fill it with empty string
preds = preds.with_columns(c.sys_msg.fill_null(""))

# reorder columns
col_names = sorted(preds.columns)
preds = preds.select(col_names)

# check if N obs per experiment is correct
nobs_error = (
    preds["exp_id"].value_counts().sort(c.exp_id)
    .filter(~c.count.is_in([5363,10020,5362, 2841]))
)
if nobs_error.height > 0:
    print("Warning: N obs per experiment incorrect for:")
    nobs_error

Warning: 1 rows failed to parse (preds_promptcast_20251018_225726)
Warning: 1 rows failed to parse (preds_promptcast_20251128_081706)
Warning: 1 rows failed to parse (preds_promptcast_20251128_104345)

In [9]:
preds[:1]

shape: (1, 54)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ act_idn_s ┆ benchmark ┆ billing_d ┆ birth_yea ┆ … ┆ transacti ┆ transacti ┆ transacti ┆ user_msg │
│ ky        ┆ _name     ┆ ates      ┆ r         ┆   ┆ on_text_s ┆ on_text_s ┆ on_text_s ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ummary_1  ┆ ummary_2  ┆ ummary_3  ┆ str      │
│ str       ┆ str       ┆ list[date ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆ ]         ┆           ┆   ┆ str       ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 001A00060 ┆ finpt     ┆ [2012-02- ┆ 1982      ┆ … ┆ null      ┆ null      ┆ null      ┆ 【信用卡 │
│ 0009658   ┆           ┆ 21, 2012- ┆           ┆   ┆           ┆           ┆           ┆ 用户信息 │
│           ┆           ┆ 03-21, …  ┆           ┆   ┆           ┆           ┆           ┆ 】：     │
│           ┆           ┆ 201…      ┆           ┆   ┆           ┆           ┆           ┆ - 居住地 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ：南京   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ - 所属分 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 支行为： │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 江…      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Run Evaluation

In [12]:
class BinaryClassificationEvaluator:
    """Evaluator for binary classification predictions with comprehensive metrics."""

    def __init__(
        self,
        data,
        target_col="target",
        pred_col="pred",
        prob_col=None,
        threshold=0.5,
        get_token_length=False,
        print_prompt=False,
    ):
        """
        Initialize the evaluator.

        Args:
            data: Polars DataFrame with target, pred, and optionally prob columns
            target_col: Name of the target column (default: "target")
            pred_col: Name of the prediction column (default: "pred")
            prob_col: Name of the probability column (default: None, optional)
            threshold: Threshold for binary classification when using probabilities (default: 0.5)
        """
        self.data = data
        self.target_col = target_col
        self.pred_col = pred_col
        self.prob_col = prob_col
        self.threshold = threshold
        self.print_prompt = print_prompt
        self.tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-30B-A3B-Thinking-2507")

        # Extract arrays
        self.y_true = data[target_col].to_numpy()
        self.y_pred = data[pred_col].to_numpy()

        # Calculate class distribution
        self.majority_class = int(self.y_true.mean() > 0.5)
        self.class_counts = pl.DataFrame({target_col: self.y_true}).group_by(target_col).len()
        self.total = len(self.y_true)

        # Check if probability column is available
        self.has_prob = (
            prob_col is not None
            and prob_col in data.columns
            and data[prob_col].null_count() < len(data)
        )

        # get average token length
        if get_token_length:
            self.avg_token_length = self.calcualte_token_length()
        else:
            self.avg_token_length = "Not calc"

    def calcualte_token_length(self):
        """Calculate the token length of a list of messages."""
        # get the messages
        messages = self.data["sys_msg"] + self.data["user_msg"]
        messages = messages.to_list()

        # Get the length of each message in tokens
        tokenized = self.tokenizer(messages, padding=False, truncation=False)
        lengths = [len(ids) for ids in tokenized["input_ids"]]

        # get average length
        return f"{np.mean(lengths):.0f}"

    def calculate_metrics(self):
        """Calculate all evaluation metrics."""
        # Calculate baseline metrics
        y_baseline = [self.majority_class] * len(self.y_true)
        self.baseline_metrics = {
            "accuracy": accuracy_score(self.y_true, y_baseline),
            "precision": precision_score(self.y_true, y_baseline, zero_division=0),
            "recall": recall_score(self.y_true, y_baseline, zero_division=0),
            "f1": f1_score(self.y_true, y_baseline, zero_division=0),
            "auc": None,
            "aupr": None,
        }

        # Calculate model metrics - use threshold-based predictions if prob_col and threshold are available
        if self.has_prob and self.threshold is not None:
            y_prob = self.data[self.prob_col].to_numpy()
            y_pred_threshold = (y_prob >= self.threshold).astype(int)

            self.metrics = {
                "accuracy": accuracy_score(self.y_true, y_pred_threshold),
                "precision": precision_score(self.y_true, y_pred_threshold, zero_division=0),
                "recall": recall_score(self.y_true, y_pred_threshold, zero_division=0),
                "f1": f1_score(self.y_true, y_pred_threshold, zero_division=0),
            }
        else:
            # Use original predictions
            self.metrics = {
                "accuracy": accuracy_score(self.y_true, self.y_pred),
                "precision": precision_score(self.y_true, self.y_pred, zero_division=0),
                "recall": recall_score(self.y_true, self.y_pred, zero_division=0),
                "f1": f1_score(self.y_true, self.y_pred, zero_division=0),
            }

        # Calculate probability-based metrics if available
        if self.has_prob:
            y_prob = self.data[self.prob_col].to_numpy()

            try:
                self.metrics["auc"] = roc_auc_score(self.y_true, y_prob)
            except (ValueError, TypeError) as e:
                print(f"Warning: Could not calculate AUC - {e}")
                self.metrics["auc"] = None

            try:
                self.metrics["aupr"] = average_precision_score(self.y_true, y_prob)
            except (ValueError, TypeError) as e:
                print(f"Warning: Could not calculate AUPR - {e}")
                self.metrics["aupr"] = None
        else:
            self.metrics["auc"] = None
            self.metrics["aupr"] = None

        return {
            "model": self.metrics,
            "baseline": self.baseline_metrics,
            "majority_class": self.majority_class,
        }

    def print_results(self):
        """Print evaluation results in a formatted table."""
        if self.print_prompt:
            print(f"[SYSTEM MESSAGE]:\n\n{self.data['sys_msg'][0]}")
            print("-" * 60)
            print()
            print(
                f"[USER MESSAGE Example]:\n\n{'\n'.join(self.data['user_msg'][0].splitlines()[:15])}"
            )
            print("...")

        print("\n" + "=" * 70)
        print("BINARY CLASSIFICATION EVALUATION RESULTS")
        print("=" * 70)

        # print experiment metadata
        exp_id = self.data["exp_id"][0]
        sample_name = Path(self.data["config_sample_path"][0]).stem
        has_protected = self.data["config_has_protected_attributes"][0]
        is_cot_prompt = self.data["config_is_cot_prompt"][0]
        llm_name = self.data["config_llm_name"][0]
        txn_text_type = self.data["config_transaction_text_type"][0]
        print(f"\nExperiment ID: {exp_id}")
        print(f"  Sample: {sample_name}")
        print(f"  Transaction Text Type: {txn_text_type}")
        print(f"  Avg Token Length: {self.avg_token_length}")
        print(f"  Is COT Prompt: {is_cot_prompt}")
        print(f"  Has Protected: {has_protected}")
        print(f"  LLM: {llm_name}")

        # Print class distribution
        print("\nClass Distribution:")
        print(f"  Total: {self.data.height:,}")
        for row in self.class_counts.iter_rows(named=True):
            class_val = row[self.class_counts.columns[0]]
            count = row["len"]
            pct = count / self.total * 100
            marker = " (MAJORITY)" if class_val == self.majority_class else ""
            print(f"  Class {class_val}: {count:,} ({pct:.2f}%){marker}")

        # Print model metrics
        print("\nModel Performance:")
        if self.has_prob and self.threshold is not None:
            print(f"  (Using threshold: {self.threshold})")
        print(f"  F1 Score:  {self.metrics['f1']:.4f}")
        print(f"  Recall:    {self.metrics['recall']:.4f}")
        print(f"  Precision: {self.metrics['precision']:.4f}")
        print(f"  Accuracy:  {self.metrics['accuracy']:.4f}")

        # Print probability-based metrics if available
        if self.has_prob and self.metrics.get("auc") is not None:
            print(f"  AUC:       {self.metrics['auc']:.4f}")
            print(f"  AUPR:      {self.metrics['aupr']:.4f}")

        print("=" * 70 + "\n")

    def evaluate(self):
        """Run full evaluation: calculate metrics and print results."""
        results = self.calculate_metrics()
        self.print_results()
        # return results


evaluator = BinaryClassificationEvaluator(
    data=(
        preds
        .filter(
            c.exp_id == "preds_promptcast_summary_1_20251204_181833",
            # c.delinquency_history.list.last() == 1,
            # c.delinquency_history.list.sum() <= 5
        )
    ),
    target_col="target_delinquency",
    pred_col="pred_is_delinquent",
    prob_col=None,
    # threshold=0.5,
    get_token_length=True,
    print_prompt=True,
)
evaluator.evaluate()

[SYSTEM MESSAGE]:

角色：你是资深金融风控建模专家，熟悉信用评分、逾期定义、卡账行为、稳定性检验。

任务：基于给定用户的个人信息和信用卡历史数据，预测其在最新一个账单周期是否能按时还款。只使用提供的数据，不要臆测缺失值。

请输出合法JSON格式（不包含 markdown code block），包含以下字段：
{
    "is_delinquent": boolean
}
------------------------------------------------------------

[USER MESSAGE Example]:

【用户信息】：
- 居住地：南京
- 所属分支行为：江苏分行
- 居住情况：未知
- 行业：未知
- 学历：未知

【消费与历史违约情况】：
该用户在过去12个账单周期中，共发生0次违约。

在2012年2月的账单周期，总支出金额为7360.0元，共发生16笔交易，

在2012年3月的账单周期，总支出金额为5271.0元，共发生16笔交易，

在2012年4月的账单周期，总支出金额为14843.0元，共发生26笔交易，
...

======================================================================
BINARY CLASSIFICATION EVALUATION RESULTS
======================================================================

Experiment ID: preds_promptcast_summary_1_20251204_181833
  Sample: samples_min12mo_fixed_2test
  Transaction Text Type: promptcast_summary_1
  Avg Token Length: 545
  Is COT Prompt: False
  Has Protected: False
  LLM: qwen2.5-7b-instruct

Class Distribution:
  Total: 5,363
  Class False: 4,924 (91.81%) (MAJORITY)
  Class True: 439 (8.19%)

Model Performance:
  F1 Score:  0.4740
  Recall:    0.5194
  Precision: 0.4359
  Accuracy:  0.9056
======================================================================

In [79]:
# old
preds_old = (
    preds.filter(c.exp_id == "preds_20251018_022543")
    .select(c.act_idn_sky, c.billing_dates, c.sys_msg, c.user_msg, c.pred_is_delinquent)
)
preds_new = (
    preds.filter(c.exp_id == "preds_20251128_030635")
    .select(c.act_idn_sky, c.billing_dates, c.sys_msg, c.user_msg, c.pred_is_delinquent)
)

df = preds_old.join(preds_new, on=["act_idn_sky", "billing_dates"], how="full")

In [80]:
print(preds_new[:1]['user_msg'].item())

【用户信息】：
- 居住地：南京
- 所属分支行为：江苏分行
- 居住情况：未知
- 行业：未知
- 学历：未知

【消费与历史违约情况】：
你过去的消费与违约情况如下：
所有用户平均逾期率(delinquency rate)为7.61%

在2012年2月的账单周期，应付账单金额为81551元，共发生16笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-01-29 20:12:04，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:15:19，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:19:02，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:21:45，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:25:12，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:32:45，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:35:21，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:38:03，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:41:45，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-02-02 10:31:26，商户类别：航空公司，交易描述：华程西南旅行社，金额960.0元。
时间：2012-02-06 11:51:21，商户类别：航空公司，交易描述：华程西南旅行社，金额440.0元。
时间：2012-02-09 08:36:30，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-02-12 18:18:32，商户类别：航空公司，交易描述：中国东方航空股份有限，金额520.0元。
时间：2012-02-15 12:54:56，商户类别：住宿服务（旅馆），交易描述：明捷置业，金额1439.97元。
时间：2012-02-16 07:52:23，商户类别：住宿服务（旅馆），交易描述：中油天宝集团国际酒店，金额280.0元。
时间：2012-02-17 15:27:11，商户类别：航空公司，交易描述：华程西南旅行社，金额920.0元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年3月的账单周期，应付账单金额为97349元，共发生16笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-02-20 08:48:08，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额100.0元。
时间：2012-02-24 12:26:04，商户类别：住宿服务（旅馆），交易描述：上海龙柏饭店有限公司，金额610.0元。
时间：2012-02-25 10:36:32，商户类别：航空公司，交易描述：华程西南旅行社，金额1240.0元。
时间：2012-02-26 19:09:20，商户类别：航空公司，交易描述：通联支付，金额259.0元。
时间：2012-03-04 13:24:17，商户类别：饮酒场所  (酒吧），交易描述：星巴克咖啡，金额120.0元。
时间：2012-03-05 12:19:19，商户类别：饮酒场所  (酒吧），交易描述：星巴克咖啡，金额32.0元。
时间：2012-03-07 10:28:42，商户类别：大型仓储式超级市场，交易描述：大连国际商贸大厦有限公，金额62.3元。
时间：2012-03-07 13:00:18，商户类别：住宿服务（旅馆），交易描述：大连银帆宾馆，金额141.0元。
时间：2012-03-07 16:26:53，商户类别：航空公司，交易描述：华程西南旅行社，金额580.0元。
时间：2012-03-09 12:26:33，商户类别：大型仓储式超级市场，交易描述：大连国际商贸大厦有限公，金额88.5元。
时间：2012-03-14 10:00:45，商户类别：住宿服务（旅馆），交易描述：中油天宝集团国际酒店，金额290.0元。
时间：2012-03-14 12:21:30，商户类别：就餐场所和餐馆，交易描述：北京将太无二餐饮有限责，金额169.0元。
时间：2012-03-15 22:19:43，商户类别：航空公司，交易描述：华程西南旅行社，金额930.0元。
时间：2012-03-16 08:11:16，商户类别：住宿服务（旅馆），交易描述：临港新城酒店投资管理公，金额375.0元。
时间：2012-03-18 16:27:15，商户类别：乳制品店、冷饮店，交易描述：苏州通用磨坊乳制品，金额151.0元。
时间：2012-03-18 18:58:38，商户类别：百货商店，交易描述：久光百货(苏州)，金额123.0元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年4月的账单周期，应付账单金额为103110元，共发生26笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-03-24 23:12:23，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额99.8元。
时间：2012-03-25 11:29:59，商户类别：普通高校（公立），交易描述：支付宝，金额29.9元。
时间：2012-03-25 11:48:05，商户类别：普通高校（公立），交易描述：支付宝，金额74.25元。
时间：2012-03-25 15:03:12，商户类别：大型仓储式超级市场，交易描述：特易购商业（辽宁）有限，金额14.0元。
时间：2012-03-25 23:19:56，商户类别：普通高校（公立），交易描述：支付宝，金额114.0元。
时间：2012-03-26 11:17:56，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额135.0元。
时间：2012-03-27 13:07:12，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-03-27 21:06:16，商户类别：会员制批量零售店，交易描述：汇付数据服务，金额89.0元。
时间：2012-03-27 21:12:13，商户类别：会员制批量零售店，交易描述：支付宝（中国）网络技术，金额144.0元。
时间：2012-03-27 23:30:37，商户类别：会员制批量零售店，交易描述：汇付数据服务，金额390.0元。
时间：2012-03-28 22:36:18，商户类别：普通高校（公立），交易描述：支付宝，金额270.0元。
时间：2012-03-29 21:48:05，商户类别：慈善和社会公益服务组织，交易描述：腾讯财付通TENPAY.COM，金额39.0元。
时间：2012-03-30 19:12:45，商户类别：普通高校（公立），交易描述：支付宝，金额41.2元。
时间：2012-04-01 14:07:39，商户类别：会员制批量零售店，交易描述：汇付数据服务，金额199.0元。
时间：2012-04-02 13:09:28，商户类别：普通高校（公立），交易描述：支付宝，金额580.0元。
时间：2012-04-06 09:21:57，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额211.0元。
时间：2012-04-06 09:57:51，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额300.0元。
时间：2012-04-06 22:56:35，商户类别：普通高校（公立），交易描述：支付宝，金额5000.0元。
时间：2012-04-07 23:34:18，商户类别：普通高校（公立），交易描述：支付宝，金额5000.0元。
时间：2012-04-08 18:49:44，商户类别：普通高校（公立），交易描述：支付宝，金额154.0元。
时间：2012-04-08 18:54:08，商户类别：普通高校（公立），交易描述：支付宝，金额58.0元。
时间：2012-04-13 19:45:38，商户类别：普通高校（公立），交易描述：支付宝，金额963.23元。
时间：2012-04-13 21:17:16，商户类别：普通高校（公立），交易描述：支付宝，金额398.0元。
时间：2012-04-15 22:17:43，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额51.58元。
时间：2012-04-16 08:41:57，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-04-17 20:08:13，商户类别：大型仓储式超级市场，交易描述：大连宜家家居有限公司，金额287.9元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年5月的账单周期，应付账单金额为105993元，共发生17笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-04-20 09:11:29，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额142.0元。
时间：2012-04-23 08:33:35，商户类别：公立医院，交易描述：大连医科大学附属第二医，金额3000.0元。
时间：2012-04-27 16:29:40，商户类别：普通高校（公立），交易描述：快钱支付，金额2799.0元。
时间：2012-04-28 20:54:22，商户类别：普通高校（公立），交易描述：支付宝，金额95.22元。
时间：2012-04-28 21:05:43，商户类别：普通高校（公立），交易描述：支付宝，金额87.75元。
时间：2012-04-28 21:37:59，商户类别：普通高校（公立），交易描述：快钱支付，金额50.8元。
时间：2012-04-28 21:52:04，商户类别：普通高校（公立），交易描述：快钱支付，金额98.0元。
时间：2012-04-29 14:18:56，商户类别：大型仓储式超级市场，交易描述：特易购商业（辽宁）有限，金额221.5元。
时间：2012-04-29 22:28:18，商户类别：保险销售、保险业和保险金，交易描述：易宝支行生产，金额98.0元。
时间：2012-05-05 17:10:23，商户类别：饮酒场所  (酒吧），交易描述：星巴克咖啡，金额37.0元。
时间：2012-05-08 09:49:26，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-05-08 15:46:12，商户类别：普通高校（公立），交易描述：支付宝，金额119.6元。
时间：2012-05-08 16:56:49，商户类别：普通高校（公立），交易描述：支付宝，金额1297.3元。
时间：2012-05-08 17:27:30，商户类别：普通高校（公立），交易描述：支付宝，金额1272.71元。
时间：2012-05-09 12:34:36，商户类别：瓶装酒零售店，交易描述：大连彬洲贸易服务中心，金额270.0元。
时间：2012-05-19 12:27:15，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额74.0元。
时间：2012-05-19 18:56:02，商户类别：慈善和社会公益服务组织，交易描述：腾讯财付通TENPAY.COM，金额218.0元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年6月的账单周期，应付账单金额为115492元，共发生19笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-05-23 13:25:37，商户类别：航空公司，交易描述：华程西南旅行社，金额1260.0元。
时间：2012-05-26 22:11:29，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额40.0元。
时间：2012-05-30 07:23:50，商户类别：住宿服务（旅馆），交易描述：芜湖国信大酒店，金额696.0元。
时间：2012-05-30 08:43:31，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-06-02 18:20:51，商户类别：就餐场所和餐馆，交易描述：苏州展圆，金额372.0元。
时间：2012-06-03 14:19:35，商户类别：航空公司，交易描述：华程西南旅行社，金额1260.0元。
时间：2012-06-04 23:00:43，商户类别：普通高校（公立），交易描述：快钱支付，金额2597.0元。
时间：2012-06-04 23:15:04，商户类别：普通高校（公立），交易描述：快钱支付，金额429.0元。
时间：2012-06-05 15:18:42，商户类别：航空公司，交易描述：华程西南旅行社，金额1030.0元。
时间：2012-06-08 22:21:40，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额40.0元。
时间：2012-06-08 22:34:57，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额35.0元。
时间：2012-06-09 16:04:32，商户类别：普通高校（公立），交易描述：支付宝，金额88.0元。
时间：2012-06-10 13:49:19，商户类别：大型仓储式超级市场，交易描述：北京华联超市苏州第四分，金额62.4元。
时间：2012-06-13 08:54:54，商户类别：住宿服务（旅馆），交易描述：上海美居虹拓酒店有限公，金额758.0元。
时间：2012-06-13 17:35:42，商户类别：慈善和社会公益服务组织，交易描述：铁道部，金额71.0元。
时间：2012-06-13 20:29:34，商户类别：普通高校（公立），交易描述：支付宝，金额138.0元。
时间：2012-06-14 10:12:15，商户类别：航空公司，交易描述：华程西南旅行社，金额1210.0元。
时间：2012-06-15 19:45:19，商户类别：慈善和社会公益服务组织，交易描述：铁道部，金额79.0元。
时间：2012-06-18 19:04:35，商户类别：瓶装酒零售店，交易描述：大连古六塔饮食文化发展，金额234.0元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年7月的账单周期，应付账单金额为121715元，共发生21笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-06-21 21:09:02，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额100.0元。
时间：2012-06-26 07:34:50，商户类别：公立医院，交易描述：大连医科大学附属第二医，金额5000.0元。
时间：2012-06-28 15:13:17，商户类别：化妆品商店，交易描述：丝芙兰（北京）化妆品销，金额177.0元。
时间：2012-06-28 18:28:12，商户类别：各类食品店及专门食品零售店，交易描述：大连艾丝碧西餐饮管理有，金额34.0元。
时间：2012-07-02 00:00:00，商户类别：计算机软件商店，交易描述：ITUNESSTORECHINA/BEIJING/，金额18.0元。
时间：2012-07-03 12:15:06，商户类别：成人成衣店，交易描述：无印良品（上海）商业大，金额1011.0元。
时间：2012-07-04 16:59:18，商户类别：成人成衣店，交易描述：无印良品（上海）商业大，金额655.0元。
时间：2012-07-06 14:31:50，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额59.0元。
时间：2012-07-06 14:33:45，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额86.0元。
时间：2012-07-07 12:09:29，商户类别：普通高校（公立），交易描述：支付宝，金额92.98元。
时间：2012-07-07 12:25:54，商户类别：会员制批量零售店，交易描述：支付宝（中国）网络技术，金额90.0元。
时间：2012-07-08 09:59:48，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额200.0元。
时间：2012-07-08 16:33:10，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额142.0元。
时间：2012-07-08 16:44:42，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额51.0元。
时间：2012-07-10 12:12:28，商户类别：航空公司，交易描述：华程西南旅行社，金额810.0元。
时间：2012-07-13 10:53:10，商户类别：航空公司，交易描述：华程西南旅行社，金额910.0元。
时间：2012-07-17 21:09:09，商户类别：普通高校（公立），交易描述：支付宝，金额440.5元。
时间：2012-07-17 21:43:50，商户类别：普通高校（公立），交易描述：支付宝，金额453.73元。
时间：2012-07-18 20:07:24，商户类别：普通高校（公立），交易描述：支付宝，金额480.0元。
时间：2012-07-18 20:58:27，商户类别：慈善和社会公益服务组织，交易描述：支付宝(MOTO)，金额747.0元。
时间：2012-07-19 22:37:18，商户类别：慈善和社会公益服务组织，交易描述：支付宝(MOTO)，金额77.0元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年8月的账单周期，应付账单金额为137221元，共发生32笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-07-20 20:25:59，商户类别：大型仓储式超级市场，交易描述：乐购(和平广场店)，金额89.15元。
时间：2012-07-20 23:34:42，商户类别：普通高校（公立），交易描述：支付宝，金额5.68元。
时间：2012-07-21 13:51:00，商户类别：保健及美容  SPA，交易描述：金石唐风国际温泉会馆，金额1717.0元。
时间：2012-07-24 12:32:12，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额2155.0元。
时间：2012-07-24 12:38:23，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额862.0元。
时间：2012-07-24 22:01:29，商户类别：航空公司，交易描述：华程西南旅行社，金额1230.0元。
时间：2012-07-26 19:52:34，商户类别：就餐场所和餐馆，交易描述：上海蕉叶连锁经营管理有，金额176.0元。
时间：2012-07-26 22:08:49，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额35.0元。
时间：2012-07-27 07:15:19，商户类别：住宿服务（旅馆），交易描述：上海明捷置业有限公司明，金额629.06元。
时间：2012-07-27 21:46:00，商户类别：慈善和社会公益服务组织，交易描述：支付宝(MOTO)，金额744.6元。
时间：2012-07-27 21:48:05，商户类别：普通高校（公立），交易描述：支付宝，金额116.6元。
时间：2012-07-27 22:03:44，商户类别：普通高校（公立），交易描述：支付宝，金额81.99元。
时间：2012-07-29 16:39:08，商户类别：慈善和社会公益服务组织，交易描述：支付宝(MOTO)，金额21.5元。
时间：2012-08-02 19:25:51，商户类别：就餐场所和餐馆，交易描述：大连经济技术开发区御竺，金额786.0元。
时间：2012-08-03 14:16:36，商户类别：航空公司，交易描述：华程西南旅行社，金额4280.0元。
时间：2012-08-03 14:25:13，商户类别：航空公司，交易描述：华程西南旅行社，金额1960.0元。
时间：2012-08-03 14:57:25，商户类别：航空公司，交易描述：华程西南旅行社，金额2220.0元。
时间：2012-08-04 16:40:16，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额6300.0元。
时间：2012-08-07 15:22:40，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额988.0元。
时间：2012-08-07 15:29:18，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额396.0元。
时间：2012-08-11 22:03:05，商户类别：航空公司，交易描述：支付宝，金额221.18元。
时间：2012-08-14 19:46:34，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额294.0元。
时间：2012-08-14 19:49:49，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额417.0元。
时间：2012-08-14 19:54:58，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额297.0元。
时间：2012-08-16 19:55:03，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额178.0元。
时间：2012-08-16 22:01:55，商户类别：航空公司，交易描述：华程西南旅行社，金额213.0元。
时间：2012-08-17 10:22:12，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额100.0元。
时间：2012-08-17 10:30:15，商户类别：大型仓储式超级市场，交易描述：江苏京东信息技术有限公，金额1099.0元。
时间：2012-08-17 20:36:06，商户类别：航空公司，交易描述：支付宝，金额109.0元。
时间：2012-08-17 21:41:51，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额1054.0元。
时间：2012-08-18 10:40:38，商户类别：航空公司，交易描述：支付宝，金额244.0元。
时间：2012-08-19 11:56:51，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额239.0元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年9月的账单周期，应付账单金额为147535元，共发生17笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-08-21 19:07:06，商户类别：就餐场所和餐馆，交易描述：大连经济技术开发区红星，金额1368.0元。
时间：2012-08-24 13:39:09，商户类别：住宿服务（旅馆），交易描述：上海龙柏饭店有限公司，金额550.0元。
时间：2012-08-28 11:22:35，商户类别：大型仓储式超级市场，交易描述：江苏京东信息技术有限公，金额48.0元。
时间：2012-08-29 19:47:55，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额294.0元。
时间：2012-08-29 23:38:53，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额200.0元。
时间：2012-09-03 09:43:45，商户类别：住宿服务（旅馆），交易描述：岷山饭店，金额740.0元。
时间：2012-09-04 09:23:32，商户类别：未知，交易描述：乐山市峨眉山风景区灵秀，金额428.0元。
时间：2012-09-04 20:38:39，商户类别：百货商店，交易描述：成都伊藤洋华堂有限公司，金额118.7元。
时间：2012-09-04 20:40:19，商户类别：百货商店，交易描述：成都伊藤洋华堂有限公司，金额145.3元。
时间：2012-09-05 11:37:14，商户类别：住宿服务（旅馆），交易描述：岷山饭店，金额740.0元。
时间：2012-09-06 21:10:48，商户类别：大型仓储式超级市场，交易描述：重庆永辉超市有限公司南，金额86.4元。
时间：2012-09-07 21:36:33，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额27.0元。
时间：2012-09-09 14:28:43，商户类别：乳制品店、冷饮店，交易描述：上海统一星巴克咖啡有限，金额60.0元。
时间：2012-09-09 19:07:07，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额35.0元。
时间：2012-09-12 12:09:56，商户类别：住宿服务（旅馆），交易描述：七彩汇商贸发展有限公司，金额846.0元。
时间：2012-09-13 22:03:14，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额1466.0元。
时间：2012-09-18 12:26:51，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额108.0元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年10月的账单周期，应付账单金额为143460元，共发生16笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-09-21 12:40:07，商户类别：就餐场所和餐馆，交易描述：大连经济技术开发区川香，金额186.0元。
时间：2012-09-24 13:55:21，商户类别：航空公司，交易描述：深圳市财付通科技有限公，金额736.0元。
时间：2012-09-29 00:00:00，商户类别：计算机软件商店，交易描述：PES*ITUNESSTORECHINA/BEIJING/，金额6.0元。
时间：2012-09-29 10:56:34，商户类别：住宿服务（旅馆），交易描述：辽宁八方大厦，金额600.0元。
时间：2012-09-30 11:51:13，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额167.0元。
时间：2012-10-02 17:45:19，商户类别：普通高校（公立），交易描述：支付宝，金额266.0元。
时间：2012-10-05 22:01:09，商户类别：普通高校（公立），交易描述：支付宝，金额59.01元。
时间：2012-10-05 22:01:56，商户类别：普通高校（公立），交易描述：支付宝，金额59.01元。
时间：2012-10-10 14:13:00，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额76.0元。
时间：2012-10-12 21:32:29，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额178.3元。
时间：2012-10-13 22:24:16，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额70.0元。
时间：2012-10-13 22:43:55，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额68.0元。
时间：2012-10-13 22:45:44，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额68.0元。
时间：2012-10-13 23:27:53，商户类别：会员制批量零售店，交易描述：支付宝（中国）网络技术，金额171.5元。
时间：2012-10-13 23:33:20，商户类别：普通高校（公立），交易描述：支付宝，金额29.3元。
时间：2012-10-19 17:55:51，商户类别：普通高校（公立），交易描述：支付宝，金额640.0元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年11月的账单周期，应付账单金额为145504元，共发生19笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-10-20 21:09:43，商户类别：普通高校（公立），交易描述：支付宝，金额20.0元。
时间：2012-10-26 15:49:31，商户类别：普通高校（公立），交易描述：联动优势电子商务有限公，金额100.0元。
时间：2012-10-31 13:59:20，商户类别：普通高校（公立），交易描述：支付宝，金额84.8元。
时间：2012-10-31 14:01:13，商户类别：普通高校（公立），交易描述：支付宝，金额78.0元。
时间：2012-10-31 14:22:03，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额95.0元。
时间：2012-10-31 22:06:54，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额124.0元。
时间：2012-11-01 22:42:32，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额22.0元。
时间：2012-11-02 09:32:21，商户类别：住宿服务（旅馆），交易描述：中油天宝集团国际酒店，金额290.0元。
时间：2012-11-07 13:46:18，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额200.0元。
时间：2012-11-07 14:03:25，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额35.0元。
时间：2012-11-11 07:59:11，商户类别：会员制批量零售店，交易描述：支付宝，金额375.3元。
时间：2012-11-11 12:58:03，商户类别：普通高校（公立），交易描述：支付宝，金额396.12元。
时间：2012-11-11 13:14:21，商户类别：会员制批量零售店，交易描述：支付宝（MOTO），金额257.5元。
时间：2012-11-11 17:32:12，商户类别：普通高校（公立），交易描述：支付宝，金额274.1元。
时间：2012-11-11 18:48:59，商户类别：普通高校（公立），交易描述：支付宝，金额160.0元。
时间：2012-11-11 18:57:31，商户类别：普通高校（公立），交易描述：支付宝，金额346.0元。
时间：2012-11-14 15:43:32，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额385.0元。
时间：2012-11-14 15:50:50，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额1886.0元。
时间：2012-11-18 12:25:58，商户类别：会员制批量零售店，交易描述：支付宝（MOTO），金额124.1元。所有用户平均逾期率(delinquency rate)为7.61%

在2012年12月的账单周期，应付账单金额为149961元，共发生21笔交易，该账单周期是否违约：否，具体消费如下：
时间：2012-11-20 21:30:48，商户类别：普通高校（公立），交易描述：支付宝，金额108.0元。
时间：2012-11-21 14:50:25，商户类别：普通高校（公立），交易描述：快钱支付，金额976.0元。
时间：2012-11-21 15:46:59，商户类别：慈善和社会公益服务组织，交易描述：腾讯财付通TENPAY.COM，金额1806.0元。
时间：2012-11-22 11:04:42，商户类别：大型仓储式家庭用品卖场，交易描述：快钱支付，金额998.0元。
时间：2012-11-22 11:21:08，商户类别：航空公司，交易描述：中国南方航空，金额1720.0元。
时间：2012-11-27 08:57:52，商户类别：慈善和社会公益服务组织，交易描述：腾讯财付通TENPAY.COM，金额426.0元。
时间：2012-11-27 09:23:23，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额76.0元。
时间：2012-11-27 09:40:22，商户类别：会员制批量零售店，交易描述：支付宝，金额261.25元。
时间：2012-11-27 09:50:52，商户类别：会员制批量零售店，交易描述：支付宝，金额530.0元。
时间：2012-12-02 12:33:06，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额65.0元。
时间：2012-12-03 10:48:33，商户类别：大型仓储式家庭用品卖场，交易描述：快钱支付，金额1308.0元。
时间：2012-12-04 11:17:15，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额234.0元。
时间：2012-12-06 14:39:54，商户类别：快餐店，交易描述：长白山国际旅游度假区开，金额82.0元。
时间：2012-12-06 21:17:12，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额12.0元。
时间：2012-12-07 07:32:52，商户类别：住宿服务（旅馆），交易描述：中油天宝集团国际酒店，金额280.0元。
时间：2012-12-08 20:59:27，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额65.0元。
时间：2012-12-08 21:06:48，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额200.0元。
时间：2012-12-12 21:50:59，商户类别：会员制批量零售店，交易描述：支付宝（MOTO），金额48.5元。
时间：2012-12-13 18:48:48，商户类别：慈善和社会公益服务组织，交易描述：苏宁易付宝，金额298.0元。
时间：2012-12-18 15:18:24，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额15.0元。
时间：2012-12-18 15:21:28，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额117.0元。所有用户平均逾期率(delinquency rate)为7.61%

（最新一个账单周期）在2013年1月的账单周期，应付账单金额为142952元，共发生11笔交易，具体消费如下：
时间：2012-12-27 15:11:35，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额116.5元。
时间：2013-01-01 19:33:41，商户类别：会员制批量零售店，交易描述：支付宝，金额283.06元。
时间：2013-01-02 00:00:00，商户类别：计算机软件商店，交易描述：PES*ITUNESSTORECHINA/BEIJING/，金额6.0元。
时间：2013-01-05 13:56:17，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额118.5元。
时间：2013-01-05 14:05:20，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额118.5元。
时间：2013-01-05 14:10:51，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额103.5元。
时间：2013-01-07 17:59:30，商户类别：普通高校（公立），交易描述：支付宝，金额300.0元。
时间：2013-01-11 11:11:52，商户类别：普通高校（公立），交易描述：联动优势电子商务有限公，金额100.0元。
时间：2013-01-18 17:36:12，商户类别：有线和其他付费电视服务，交易描述：联动优势电子商务有限公，金额1164.0元。
时间：2013-01-19 21:27:00，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额49.0元。
时间：2013-01-19 21:29:45，商户类别：普通高校（公立），交易描述：支付宝，金额149.0元。

In [46]:
with pl.Config(fmt_str_lengths=100):
    df.select(c.user_msg, c.user_msg_right).sample()

shape: (1, 2)
┌──────────────────────────────┬──────────────────────────────┐
│ user_msg                     ┆ user_msg_right               │
│ ---                          ┆ ---                          │
│ str                          ┆ str                          │
╞══════════════════════════════╪══════════════════════════════╡
│ 【用户信息】：               ┆ 【用户信息】：               │
│ - 居住地：南京               ┆ - 居住地：南京               │
│ - 所属分支行为：None         ┆ - 所属分支行为：None         │
│ - 居住情况：无按揭自置       ┆ - 居住情况：无按揭自置       │
│ - 行业：能源                 ┆ - 行业：能源                 │
│ - 学历：大学本科             ┆ - 学历：大学本科             │
│                              ┆                              │
│ 【消费与历史违约情况】：     ┆ 【消费与历史违约情况】：     │
│ 你过去的消费与违约情况如下： ┆ 你过去的消费与违约情况如下： │
│ 在2012年3月的…               ┆ 在2012年3月的…               │
└──────────────────────────────┴──────────────────────────────┘

In [26]:
# print(preds_old[:1]['sys_msg'].item())
print(preds_old[:1]['user_msg'].item())

【用户信息】：
- 居住地：南京
- 所属分支行为：江苏分行
- 居住情况：未知
- 行业：未知
- 学历：未知

【消费与历史违约情况】：
你过去的消费与违约情况如下：
在2012年2月的账单周期，应付账单金额为81551元，该账单周期是否违约：否，具体消费如下：
时间：2012-01-29 20:12:04，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:15:19，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:19:02，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:21:45，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:25:12，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:32:45，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:35:21，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:38:03，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-01-29 20:41:45，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额300.0元。
时间：2012-02-02 10:31:26，商户类别：航空公司，交易描述：华程西南旅行社，金额960.0元。
时间：2012-02-06 11:51:21，商户类别：航空公司，交易描述：华程西南旅行社，金额440.0元。
时间：2012-02-09 08:36:30，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-02-12 18:18:32，商户类别：航空公司，交易描述：中国东方航空股份有限，金额520.0元。
时间：2012-02-15 12:54:56，商户类别：住宿服务（旅馆），交易描述：明捷置业，金额1439.97元。
时间：2012-02-16 07:52:23，商户类别：住宿服务（旅馆），交易描述：中油天宝集团国际酒店，金额280.0元。
时间：2012-02-17 15:27:11，商户类别：航空公司，交易描述：华程西南旅行社，金额920.0元。

在2012年3月的账单周期，应付账单金额为97349元，该账单周期是否违约：否，具体消费如下：
时间：2012-02-20 08:48:08，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额100.0元。
时间：2012-02-24 12:26:04，商户类别：住宿服务（旅馆），交易描述：上海龙柏饭店有限公司，金额610.0元。
时间：2012-02-25 10:36:32，商户类别：航空公司，交易描述：华程西南旅行社，金额1240.0元。
时间：2012-02-26 19:09:20，商户类别：航空公司，交易描述：通联支付，金额259.0元。
时间：2012-03-04 13:24:17，商户类别：饮酒场所  (酒吧），交易描述：星巴克咖啡，金额120.0元。
时间：2012-03-05 12:19:19，商户类别：饮酒场所  (酒吧），交易描述：星巴克咖啡，金额32.0元。
时间：2012-03-07 10:28:42，商户类别：大型仓储式超级市场，交易描述：大连国际商贸大厦有限公，金额62.3元。
时间：2012-03-07 13:00:18，商户类别：住宿服务（旅馆），交易描述：大连银帆宾馆，金额141.0元。
时间：2012-03-07 16:26:53，商户类别：航空公司，交易描述：华程西南旅行社，金额580.0元。
时间：2012-03-09 12:26:33，商户类别：大型仓储式超级市场，交易描述：大连国际商贸大厦有限公，金额88.5元。
时间：2012-03-14 10:00:45，商户类别：住宿服务（旅馆），交易描述：中油天宝集团国际酒店，金额290.0元。
时间：2012-03-14 12:21:30，商户类别：就餐场所和餐馆，交易描述：北京将太无二餐饮有限责，金额169.0元。
时间：2012-03-15 22:19:43，商户类别：航空公司，交易描述：华程西南旅行社，金额930.0元。
时间：2012-03-16 08:11:16，商户类别：住宿服务（旅馆），交易描述：临港新城酒店投资管理公，金额375.0元。
时间：2012-03-18 16:27:15，商户类别：乳制品店、冷饮店，交易描述：苏州通用磨坊乳制品，金额151.0元。
时间：2012-03-18 18:58:38，商户类别：百货商店，交易描述：久光百货(苏州)，金额123.0元。

在2012年4月的账单周期，应付账单金额为103110元，该账单周期是否违约：否，具体消费如下：
时间：2012-03-24 23:12:23，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额99.8元。
时间：2012-03-25 11:29:59，商户类别：普通高校（公立），交易描述：支付宝，金额29.9元。
时间：2012-03-25 11:48:05，商户类别：普通高校（公立），交易描述：支付宝，金额74.25元。
时间：2012-03-25 15:03:12，商户类别：大型仓储式超级市场，交易描述：特易购商业（辽宁）有限，金额14.0元。
时间：2012-03-25 23:19:56，商户类别：普通高校（公立），交易描述：支付宝，金额114.0元。
时间：2012-03-26 11:17:56，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额135.0元。
时间：2012-03-27 13:07:12，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-03-27 21:06:16，商户类别：会员制批量零售店，交易描述：汇付数据服务，金额89.0元。
时间：2012-03-27 21:12:13，商户类别：会员制批量零售店，交易描述：支付宝（中国）网络技术，金额144.0元。
时间：2012-03-27 23:30:37，商户类别：会员制批量零售店，交易描述：汇付数据服务，金额390.0元。
时间：2012-03-28 22:36:18，商户类别：普通高校（公立），交易描述：支付宝，金额270.0元。
时间：2012-03-29 21:48:05，商户类别：慈善和社会公益服务组织，交易描述：腾讯财付通TENPAY.COM，金额39.0元。
时间：2012-03-30 19:12:45，商户类别：普通高校（公立），交易描述：支付宝，金额41.2元。
时间：2012-04-01 14:07:39，商户类别：会员制批量零售店，交易描述：汇付数据服务，金额199.0元。
时间：2012-04-02 13:09:28，商户类别：普通高校（公立），交易描述：支付宝，金额580.0元。
时间：2012-04-06 09:21:57，商户类别：慈善和社会公益服务组织，交易描述：支付宝，金额211.0元。
时间：2012-04-06 09:57:51，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额300.0元。
时间：2012-04-06 22:56:35，商户类别：普通高校（公立），交易描述：支付宝，金额5000.0元。
时间：2012-04-07 23:34:18，商户类别：普通高校（公立），交易描述：支付宝，金额5000.0元。
时间：2012-04-08 18:49:44，商户类别：普通高校（公立），交易描述：支付宝，金额154.0元。
时间：2012-04-08 18:54:08，商户类别：普通高校（公立），交易描述：支付宝，金额58.0元。
时间：2012-04-13 19:45:38，商户类别：普通高校（公立），交易描述：支付宝，金额963.23元。
时间：2012-04-13 21:17:16，商户类别：普通高校（公立），交易描述：支付宝，金额398.0元。
时间：2012-04-15 22:17:43，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额51.58元。
时间：2012-04-16 08:41:57，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-04-17 20:08:13，商户类别：大型仓储式超级市场，交易描述：大连宜家家居有限公司，金额287.9元。

在2012年5月的账单周期，应付账单金额为105993元，该账单周期是否违约：否，具体消费如下：
时间：2012-04-20 09:11:29，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额142.0元。
时间：2012-04-23 08:33:35，商户类别：公立医院，交易描述：大连医科大学附属第二医，金额3000.0元。
时间：2012-04-27 16:29:40，商户类别：普通高校（公立），交易描述：快钱支付，金额2799.0元。
时间：2012-04-28 20:54:22，商户类别：普通高校（公立），交易描述：支付宝，金额95.22元。
时间：2012-04-28 21:05:43，商户类别：普通高校（公立），交易描述：支付宝，金额87.75元。
时间：2012-04-28 21:37:59，商户类别：普通高校（公立），交易描述：快钱支付，金额50.8元。
时间：2012-04-28 21:52:04，商户类别：普通高校（公立），交易描述：快钱支付，金额98.0元。
时间：2012-04-29 14:18:56，商户类别：大型仓储式超级市场，交易描述：特易购商业（辽宁）有限，金额221.5元。
时间：2012-04-29 22:28:18，商户类别：保险销售、保险业和保险金，交易描述：易宝支行生产，金额98.0元。
时间：2012-05-05 17:10:23，商户类别：饮酒场所  (酒吧），交易描述：星巴克咖啡，金额37.0元。
时间：2012-05-08 09:49:26，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-05-08 15:46:12，商户类别：普通高校（公立），交易描述：支付宝，金额119.6元。
时间：2012-05-08 16:56:49，商户类别：普通高校（公立），交易描述：支付宝，金额1297.3元。
时间：2012-05-08 17:27:30，商户类别：普通高校（公立），交易描述：支付宝，金额1272.71元。
时间：2012-05-09 12:34:36，商户类别：瓶装酒零售店，交易描述：大连彬洲贸易服务中心，金额270.0元。
时间：2012-05-19 12:27:15，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额74.0元。
时间：2012-05-19 18:56:02，商户类别：慈善和社会公益服务组织，交易描述：腾讯财付通TENPAY.COM，金额218.0元。

在2012年6月的账单周期，应付账单金额为115492元，该账单周期是否违约：否，具体消费如下：
时间：2012-05-23 13:25:37，商户类别：航空公司，交易描述：华程西南旅行社，金额1260.0元。
时间：2012-05-26 22:11:29，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额40.0元。
时间：2012-05-30 07:23:50，商户类别：住宿服务（旅馆），交易描述：芜湖国信大酒店，金额696.0元。
时间：2012-05-30 08:43:31，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额100.0元。
时间：2012-06-02 18:20:51，商户类别：就餐场所和餐馆，交易描述：苏州展圆，金额372.0元。
时间：2012-06-03 14:19:35，商户类别：航空公司，交易描述：华程西南旅行社，金额1260.0元。
时间：2012-06-04 23:00:43，商户类别：普通高校（公立），交易描述：快钱支付，金额2597.0元。
时间：2012-06-04 23:15:04，商户类别：普通高校（公立），交易描述：快钱支付，金额429.0元。
时间：2012-06-05 15:18:42，商户类别：航空公司，交易描述：华程西南旅行社，金额1030.0元。
时间：2012-06-08 22:21:40，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额40.0元。
时间：2012-06-08 22:34:57，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额35.0元。
时间：2012-06-09 16:04:32，商户类别：普通高校（公立），交易描述：支付宝，金额88.0元。
时间：2012-06-10 13:49:19，商户类别：大型仓储式超级市场，交易描述：北京华联超市苏州第四分，金额62.4元。
时间：2012-06-13 08:54:54，商户类别：住宿服务（旅馆），交易描述：上海美居虹拓酒店有限公，金额758.0元。
时间：2012-06-13 17:35:42，商户类别：慈善和社会公益服务组织，交易描述：铁道部，金额71.0元。
时间：2012-06-13 20:29:34，商户类别：普通高校（公立），交易描述：支付宝，金额138.0元。
时间：2012-06-14 10:12:15，商户类别：航空公司，交易描述：华程西南旅行社，金额1210.0元。
时间：2012-06-15 19:45:19，商户类别：慈善和社会公益服务组织，交易描述：铁道部，金额79.0元。
时间：2012-06-18 19:04:35，商户类别：瓶装酒零售店，交易描述：大连古六塔饮食文化发展，金额234.0元。

在2012年7月的账单周期，应付账单金额为121715元，该账单周期是否违约：否，具体消费如下：
时间：2012-06-21 21:09:02，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额100.0元。
时间：2012-06-26 07:34:50，商户类别：公立医院，交易描述：大连医科大学附属第二医，金额5000.0元。
时间：2012-06-28 15:13:17，商户类别：化妆品商店，交易描述：丝芙兰（北京）化妆品销，金额177.0元。
时间：2012-06-28 18:28:12，商户类别：各类食品店及专门食品零售店，交易描述：大连艾丝碧西餐饮管理有，金额34.0元。
时间：2012-07-02 00:00:00，商户类别：计算机软件商店，交易描述：ITUNESSTORECHINA/BEIJING/，金额18.0元。
时间：2012-07-03 12:15:06，商户类别：成人成衣店，交易描述：无印良品（上海）商业大，金额1011.0元。
时间：2012-07-04 16:59:18，商户类别：成人成衣店，交易描述：无印良品（上海）商业大，金额655.0元。
时间：2012-07-06 14:31:50，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额59.0元。
时间：2012-07-06 14:33:45，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额86.0元。
时间：2012-07-07 12:09:29，商户类别：普通高校（公立），交易描述：支付宝，金额92.98元。
时间：2012-07-07 12:25:54，商户类别：会员制批量零售店，交易描述：支付宝（中国）网络技术，金额90.0元。
时间：2012-07-08 09:59:48，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额200.0元。
时间：2012-07-08 16:33:10，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额142.0元。
时间：2012-07-08 16:44:42，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额51.0元。
时间：2012-07-10 12:12:28，商户类别：航空公司，交易描述：华程西南旅行社，金额810.0元。
时间：2012-07-13 10:53:10，商户类别：航空公司，交易描述：华程西南旅行社，金额910.0元。
时间：2012-07-17 21:09:09，商户类别：普通高校（公立），交易描述：支付宝，金额440.5元。
时间：2012-07-17 21:43:50，商户类别：普通高校（公立），交易描述：支付宝，金额453.73元。
时间：2012-07-18 20:07:24，商户类别：普通高校（公立），交易描述：支付宝，金额480.0元。
时间：2012-07-18 20:58:27，商户类别：慈善和社会公益服务组织，交易描述：支付宝(MOTO)，金额747.0元。
时间：2012-07-19 22:37:18，商户类别：慈善和社会公益服务组织，交易描述：支付宝(MOTO)，金额77.0元。

在2012年8月的账单周期，应付账单金额为137221元，该账单周期是否违约：否，具体消费如下：
时间：2012-07-20 20:25:59，商户类别：大型仓储式超级市场，交易描述：乐购(和平广场店)，金额89.15元。
时间：2012-07-20 23:34:42，商户类别：普通高校（公立），交易描述：支付宝，金额5.68元。
时间：2012-07-21 13:51:00，商户类别：保健及美容  SPA，交易描述：金石唐风国际温泉会馆，金额1717.0元。
时间：2012-07-24 12:32:12，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额2155.0元。
时间：2012-07-24 12:38:23，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额862.0元。
时间：2012-07-24 22:01:29，商户类别：航空公司，交易描述：华程西南旅行社，金额1230.0元。
时间：2012-07-26 19:52:34，商户类别：就餐场所和餐馆，交易描述：上海蕉叶连锁经营管理有，金额176.0元。
时间：2012-07-26 22:08:49，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额35.0元。
时间：2012-07-27 07:15:19，商户类别：住宿服务（旅馆），交易描述：上海明捷置业有限公司明，金额629.06元。
时间：2012-07-27 21:46:00，商户类别：慈善和社会公益服务组织，交易描述：支付宝(MOTO)，金额744.6元。
时间：2012-07-27 21:48:05，商户类别：普通高校（公立），交易描述：支付宝，金额116.6元。
时间：2012-07-27 22:03:44，商户类别：普通高校（公立），交易描述：支付宝，金额81.99元。
时间：2012-07-29 16:39:08，商户类别：慈善和社会公益服务组织，交易描述：支付宝(MOTO)，金额21.5元。
时间：2012-08-02 19:25:51，商户类别：就餐场所和餐馆，交易描述：大连经济技术开发区御竺，金额786.0元。
时间：2012-08-03 14:16:36，商户类别：航空公司，交易描述：华程西南旅行社，金额4280.0元。
时间：2012-08-03 14:25:13，商户类别：航空公司，交易描述：华程西南旅行社，金额1960.0元。
时间：2012-08-03 14:57:25，商户类别：航空公司，交易描述：华程西南旅行社，金额2220.0元。
时间：2012-08-04 16:40:16，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额6300.0元。
时间：2012-08-07 15:22:40，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额988.0元。
时间：2012-08-07 15:29:18，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额396.0元。
时间：2012-08-11 22:03:05，商户类别：航空公司，交易描述：支付宝，金额221.18元。
时间：2012-08-14 19:46:34，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额294.0元。
时间：2012-08-14 19:49:49，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额417.0元。
时间：2012-08-14 19:54:58，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额297.0元。
时间：2012-08-16 19:55:03，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额178.0元。
时间：2012-08-16 22:01:55，商户类别：航空公司，交易描述：华程西南旅行社，金额213.0元。
时间：2012-08-17 10:22:12，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额100.0元。
时间：2012-08-17 10:30:15，商户类别：大型仓储式超级市场，交易描述：江苏京东信息技术有限公，金额1099.0元。
时间：2012-08-17 20:36:06，商户类别：航空公司，交易描述：支付宝，金额109.0元。
时间：2012-08-17 21:41:51，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额1054.0元。
时间：2012-08-18 10:40:38，商户类别：航空公司，交易描述：支付宝，金额244.0元。
时间：2012-08-19 11:56:51，商户类别：慈善和社会公益服务组织，交易描述：快钱支付，金额239.0元。

在2012年9月的账单周期，应付账单金额为147535元，该账单周期是否违约：否，具体消费如下：
时间：2012-08-21 19:07:06，商户类别：就餐场所和餐馆，交易描述：大连经济技术开发区红星，金额1368.0元。
时间：2012-08-24 13:39:09，商户类别：住宿服务（旅馆），交易描述：上海龙柏饭店有限公司，金额550.0元。
时间：2012-08-28 11:22:35，商户类别：大型仓储式超级市场，交易描述：江苏京东信息技术有限公，金额48.0元。
时间：2012-08-29 19:47:55，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额294.0元。
时间：2012-08-29 23:38:53，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额200.0元。
时间：2012-09-03 09:43:45，商户类别：住宿服务（旅馆），交易描述：岷山饭店，金额740.0元。
时间：2012-09-04 09:23:32，商户类别：未知，交易描述：乐山市峨眉山风景区灵秀，金额428.0元。
时间：2012-09-04 20:38:39，商户类别：百货商店，交易描述：成都伊藤洋华堂有限公司，金额118.7元。
时间：2012-09-04 20:40:19，商户类别：百货商店，交易描述：成都伊藤洋华堂有限公司，金额145.3元。
时间：2012-09-05 11:37:14，商户类别：住宿服务（旅馆），交易描述：岷山饭店，金额740.0元。
时间：2012-09-06 21:10:48，商户类别：大型仓储式超级市场，交易描述：重庆永辉超市有限公司南，金额86.4元。
时间：2012-09-07 21:36:33，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额27.0元。
时间：2012-09-09 14:28:43，商户类别：乳制品店、冷饮店，交易描述：上海统一星巴克咖啡有限，金额60.0元。
时间：2012-09-09 19:07:07，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额35.0元。
时间：2012-09-12 12:09:56，商户类别：住宿服务（旅馆），交易描述：七彩汇商贸发展有限公司，金额846.0元。
时间：2012-09-13 22:03:14，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额1466.0元。
时间：2012-09-18 12:26:51，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额108.0元。

在2012年10月的账单周期，应付账单金额为143460元，该账单周期是否违约：否，具体消费如下：
时间：2012-09-21 12:40:07，商户类别：就餐场所和餐馆，交易描述：大连经济技术开发区川香，金额186.0元。
时间：2012-09-24 13:55:21，商户类别：航空公司，交易描述：深圳市财付通科技有限公，金额736.0元。
时间：2012-09-29 00:00:00，商户类别：计算机软件商店，交易描述：PES*ITUNESSTORECHINA/BEIJING/，金额6.0元。
时间：2012-09-29 10:56:34，商户类别：住宿服务（旅馆），交易描述：辽宁八方大厦，金额600.0元。
时间：2012-09-30 11:51:13，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额167.0元。
时间：2012-10-02 17:45:19，商户类别：普通高校（公立），交易描述：支付宝，金额266.0元。
时间：2012-10-05 22:01:09，商户类别：普通高校（公立），交易描述：支付宝，金额59.01元。
时间：2012-10-05 22:01:56，商户类别：普通高校（公立），交易描述：支付宝，金额59.01元。
时间：2012-10-10 14:13:00，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额76.0元。
时间：2012-10-12 21:32:29，商户类别：会员制批量零售店，交易描述：支付宝(MOTO)，金额178.3元。
时间：2012-10-13 22:24:16，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额70.0元。
时间：2012-10-13 22:43:55，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额68.0元。
时间：2012-10-13 22:45:44，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额68.0元。
时间：2012-10-13 23:27:53，商户类别：会员制批量零售店，交易描述：支付宝（中国）网络技术，金额171.5元。
时间：2012-10-13 23:33:20，商户类别：普通高校（公立），交易描述：支付宝，金额29.3元。
时间：2012-10-19 17:55:51，商户类别：普通高校（公立），交易描述：支付宝，金额640.0元。

在2012年11月的账单周期，应付账单金额为145504元，该账单周期是否违约：否，具体消费如下：
时间：2012-10-20 21:09:43，商户类别：普通高校（公立），交易描述：支付宝，金额20.0元。
时间：2012-10-26 15:49:31，商户类别：普通高校（公立），交易描述：联动优势电子商务有限公，金额100.0元。
时间：2012-10-31 13:59:20，商户类别：普通高校（公立），交易描述：支付宝，金额84.8元。
时间：2012-10-31 14:01:13，商户类别：普通高校（公立），交易描述：支付宝，金额78.0元。
时间：2012-10-31 14:22:03，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额95.0元。
时间：2012-10-31 22:06:54，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额124.0元。
时间：2012-11-01 22:42:32，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额22.0元。
时间：2012-11-02 09:32:21，商户类别：住宿服务（旅馆），交易描述：中油天宝集团国际酒店，金额290.0元。
时间：2012-11-07 13:46:18，商户类别：大型仓储式家庭用品卖场，交易描述：中国移动通信集团江苏有，金额200.0元。
时间：2012-11-07 14:03:25，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额35.0元。
时间：2012-11-11 07:59:11，商户类别：会员制批量零售店，交易描述：支付宝，金额375.3元。
时间：2012-11-11 12:58:03，商户类别：普通高校（公立），交易描述：支付宝，金额396.12元。
时间：2012-11-11 13:14:21，商户类别：会员制批量零售店，交易描述：支付宝（MOTO），金额257.5元。
时间：2012-11-11 17:32:12，商户类别：普通高校（公立），交易描述：支付宝，金额274.1元。
时间：2012-11-11 18:48:59，商户类别：普通高校（公立），交易描述：支付宝，金额160.0元。
时间：2012-11-11 18:57:31，商户类别：普通高校（公立），交易描述：支付宝，金额346.0元。
时间：2012-11-14 15:43:32，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额385.0元。
时间：2012-11-14 15:50:50，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额1886.0元。
时间：2012-11-18 12:25:58，商户类别：会员制批量零售店，交易描述：支付宝（MOTO），金额124.1元。

在2012年12月的账单周期，应付账单金额为149961元，该账单周期是否违约：否，具体消费如下：
时间：2012-11-20 21:30:48，商户类别：普通高校（公立），交易描述：支付宝，金额108.0元。
时间：2012-11-21 14:50:25，商户类别：普通高校（公立），交易描述：快钱支付，金额976.0元。
时间：2012-11-21 15:46:59，商户类别：慈善和社会公益服务组织，交易描述：腾讯财付通TENPAY.COM，金额1806.0元。
时间：2012-11-22 11:04:42，商户类别：大型仓储式家庭用品卖场，交易描述：快钱支付，金额998.0元。
时间：2012-11-22 11:21:08，商户类别：航空公司，交易描述：中国南方航空，金额1720.0元。
时间：2012-11-27 08:57:52，商户类别：慈善和社会公益服务组织，交易描述：腾讯财付通TENPAY.COM，金额426.0元。
时间：2012-11-27 09:23:23，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额76.0元。
时间：2012-11-27 09:40:22，商户类别：会员制批量零售店，交易描述：支付宝，金额261.25元。
时间：2012-11-27 09:50:52，商户类别：会员制批量零售店，交易描述：支付宝，金额530.0元。
时间：2012-12-02 12:33:06，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额65.0元。
时间：2012-12-03 10:48:33，商户类别：大型仓储式家庭用品卖场，交易描述：快钱支付，金额1308.0元。
时间：2012-12-04 11:17:15，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额234.0元。
时间：2012-12-06 14:39:54，商户类别：快餐店，交易描述：长白山国际旅游度假区开，金额82.0元。
时间：2012-12-06 21:17:12，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额12.0元。
时间：2012-12-07 07:32:52，商户类别：住宿服务（旅馆），交易描述：中油天宝集团国际酒店，金额280.0元。
时间：2012-12-08 20:59:27，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额65.0元。
时间：2012-12-08 21:06:48，商户类别：慈善和社会公益服务组织，交易描述：中国银联，金额200.0元。
时间：2012-12-12 21:50:59，商户类别：会员制批量零售店，交易描述：支付宝（MOTO），金额48.5元。
时间：2012-12-13 18:48:48，商户类别：慈善和社会公益服务组织，交易描述：苏宁易付宝，金额298.0元。
时间：2012-12-18 15:18:24，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额15.0元。
时间：2012-12-18 15:21:28，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额117.0元。

在2013年1月的账单周期，应付账单金额为142952元，具体消费如下：
时间：2012-12-27 15:11:35，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额116.5元。
时间：2013-01-01 19:33:41，商户类别：会员制批量零售店，交易描述：支付宝，金额283.06元。
时间：2013-01-02 00:00:00，商户类别：计算机软件商店，交易描述：PES*ITUNESSTORECHINA/BEIJING/，金额6.0元。
时间：2013-01-05 13:56:17，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额118.5元。
时间：2013-01-05 14:05:20，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额118.5元。
时间：2013-01-05 14:10:51，商户类别：未列入其他代码的政府服务，交易描述：铁道部资金清算中心，金额103.5元。
时间：2013-01-07 17:59:30，商户类别：普通高校（公立），交易描述：支付宝，金额300.0元。
时间：2013-01-11 11:11:52，商户类别：普通高校（公立），交易描述：联动优势电子商务有限公，金额100.0元。
时间：2013-01-18 17:36:12，商户类别：有线和其他付费电视服务，交易描述：联动优势电子商务有限公，金额1164.0元。
时间：2013-01-19 21:27:00，商户类别：普通高校（公立），交易描述：快钱快捷支付，金额49.0元。
时间：2013-01-19 21:29:45，商户类别：普通高校（公立），交易描述：支付宝，金额149.0元。

### Logistic

In [9]:
def calc_metrics(x_train, y_train, x_test, y_test):

    # Train logistic regression model
    lr_model = LogisticRegression(max_iter=1000)
    lr_model.fit(x_train, y_train)

    # Predict on test set
    y_pred = lr_model.predict(x_test)

    # Calculate metrics (with zero_division=0 to suppress warnings)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    precision = precision_score(y_test, y_pred, zero_division=0)
    accuracy = accuracy_score(y_test, y_pred)

    print(f"Logistic Regression Results on Test Set:")
    print(f"  N: {len(y_test)}")
    print(f"  F1 Score: {f1:.4f}")
    print(f"  Recall: {recall:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Accuracy: {accuracy:.4f}")

delin = cum_delin

In [15]:
# load sample index
samples = pl.read_ipc("data/processed_data/llm_benchmark/samples_min12mo_fixed_2test.feather", memory_map=False)

# Use cum_delin as features
x_test = samples.filter(c.split == "test").select(c.cumulative_delin_times).to_numpy().reshape(-1, 1)
y_test = samples.filter(c.split == "test").select(c.target_delinquency).to_numpy().ravel()
x_test_firsttime = (
    samples
    .filter(c.split == "test", c.delinquency_history.list.last(), c.delinquency_history.list.sum() <= 3)
    .select(c.cumulative_delin_times)
    .to_numpy()
    .reshape(-1, 1)
)
y_test_firsttime = (
    samples.filter(c.split == "test", c.delinquency_history.list.last(), c.delinquency_history.list.sum() <= 3)
    .select(c.target_delinquency)
    .to_numpy()
    .ravel()
)

x_train = samples.filter(c.split == "train").select(c.cumulative_delin_times).to_numpy().reshape(-1, 1)
y_train = samples.filter(c.split == "train").select(c.target_delinquency).to_numpy().ravel()

print("=" * 80)
print("ALL TEST SAMPLES")
print("=" * 80)
calc_metrics(x_train, y_train, x_test, y_test)

print("\n" + "=" * 80)
print("FIRST-TIME DELINQUENCY TEST SAMPLES")
print("=" * 80)
calc_metrics(x_train, y_train, x_test_firsttime, y_test_firsttime)
print("=" * 80)

================================================================================
ALL TEST SAMPLES
================================================================================
Logistic Regression Results on Test Set:
  N: 5363
  F1 Score: 0.4259
  Recall: 0.3144
  Precision: 0.6603
  Accuracy: 0.9306

================================================================================
FIRST-TIME DELINQUENCY TEST SAMPLES
================================================================================
Logistic Regression Results on Test Set:
  N: 201
  F1 Score: 0.0000
  Recall: 0.0000
  Precision: 0.0000
  Accuracy: 0.0000
================================================================================

delin = cum_delin + total_amt + N txn

In [99]:
# load sample index
samples = pl.read_ipc("data/processed_data/llm_benchmark/samples_min12mo_fixed_2test.feather", memory_map=False)

# Use cum_delin as features
data = (
    samples
    .select(c.split, c.delinquency_history, c.cumulative_delin_times, c.total_amt, c.n_txn, c.target_delinquency)
    .with_columns(c.total_amt.list.to_struct(fields=[f"total_amt_{i}" for i in range(12)]))
    .with_columns(c.n_txn.list.to_struct(fields=[f"n_txn_{i}" for i in range(12)]))
    .unnest("total_amt")
    .unnest("n_txn")
)

x_test = (
    data
    .filter(c.split == 'test')
    .select(c.cumulative_delin_times, pl.col([f"total_amt_{i}" for i in range(12)]), pl.col([f"n_txn_{i}" for i in range(12)]))
    .to_numpy()
)
y_test = (
    data
    .filter(c.split == 'test')
    .select(c.target_delinquency)
    .to_numpy()
    .ravel()
)

# First-time delinquency test samples
x_test_firsttime = (
    data
    .filter(c.split == 'test', c.delinquency_history.list.last(), c.delinquency_history.list.sum()<=2)
    .select(c.cumulative_delin_times, pl.col([f"total_amt_{i}" for i in range(12)]), pl.col([f"n_txn_{i}" for i in range(12)]))
    .to_numpy()
)
y_test_firsttime = (
    data
    .filter(c.split == 'test', c.delinquency_history.list.last(), c.delinquency_history.list.sum()<=2)
    .select(c.target_delinquency)
    .to_numpy()
    .ravel()
)

x_train = (
    data
    .filter(c.split == 'train')
    .select(c.cumulative_delin_times, pl.col([f"total_amt_{i}" for i in range(12)]), pl.col([f"n_txn_{i}" for i in range(12)]))
    .to_numpy()
)
y_train = (
    data
    .filter(c.split == 'train')
    .select(c.target_delinquency)
    .to_numpy()
    .ravel()
)

print("=" * 80)
print("MULTI-FEATURE LOGISTIC REGRESSION - ALL TEST SAMPLES")
print("=" * 80)
calc_metrics(x_train, y_train, x_test, y_test)

print("\n" + "=" * 80)
print("MULTI-FEATURE LOGISTIC REGRESSION - FIRST-TIME DELINQUENCY")
print("=" * 80)
calc_metrics(x_train, y_train, x_test_firsttime, y_test_firsttime)
print("=" * 80)

================================================================================
MULTI-FEATURE LOGISTIC REGRESSION - ALL TEST SAMPLES
================================================================================

/home/yuzhu/App/python-env/py312/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression Results on Test Set:
  F1 Score: 0.4106
  Recall: 0.3166
  Precision: 0.5840
  Accuracy: 0.9256

================================================================================
MULTI-FEATURE LOGISTIC REGRESSION - FIRST-TIME DELINQUENCY
================================================================================
Logistic Regression Results on Test Set:
  F1 Score: 0.0000
  Recall: 0.0000
  Precision: 0.0000
  Accuracy: 0.0000
================================================================================

/home/yuzhu/App/python-env/py312/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## Sketch

In [3]:
# load sample index
samples = pl.read_ipc("data/processed_data/llm_benchmark/samples_min12mo_fixed_2test.feather", memory_map=False)
sample_index = pl.read_ipc("data/processed_data/sample_index/index_min12mo_fixed_2test.feather", memory_map=False)

# load transaction data
transactions = pl.read_ipc("data/raw_data/sample_transaction.feather", memory_map=False)

# load prediction results
preds = pl.read_ipc("data/processed_data/llm_benchmark/preds_promptcast_detail_1_20251205_020652.feather", memory_map=False)

# load embeddings
# emb34 = torch.load("data/processed_data/llm_benchmark/embeds_finpt_detail_1_20251204_155334.pt")
# emb51 = torch.load("data/processed_data/llm_benchmark/embeds_finpt_detail_1_20251204_214351.pt")

In [6]:
preds[:1]['pred_is_delinquent_raw'].item()

'```json\n{\n    "is_delinquent": false\n}\n```'

In [26]:
sum([1 for ele in emb34 if ele['embedding'] is None])
sum([1 for ele in emb51 if ele['embedding'] is None])

10

22586

In [8]:
len(emb34)
sum([(e1['embedding'] == e2['embedding']).all() for e1, e2 in zip(emb34, emb43)])

22586

tensor(22586)

In [53]:
emb43[987]['embedding']
emb34[987]['embedding']

tensor([-0.0011, -0.0023, -0.0030,  ..., -0.0015, -0.0012, -0.0011])

tensor([-0.0011, -0.0023, -0.0030,  ..., -0.0015, -0.0012, -0.0011])

In [90]:
with pl.Config(set_fmt_table_cell_list_len=1000):
    (
        samples
        .filter(c.split == 'test')
        .with_columns(c.delinquency_history.list.eval(pl.element().cast(pl.Int64)))
        # find the delinquent samples
        .filter(c.delinquency_history.list.last()==1)
        # delinquency 1 time or less
        # .filter(c.delinquency_history.list.sum()<=2)
        ['delinquency_history'].value_counts(sort=True)
        .with_columns(proportion=(c.count/c.count.sum()).round(4), n=c.count.sum())
        # get first-time delinquency
        # .filter(c.delinquency_history==[0,0,0,0,0,0,0,0,0,0,0,1])
    )

shape: (265, 4)
┌─────────────────────────────────┬───────┬────────────┬─────┐
│ delinquency_history             ┆ count ┆ proportion ┆ n   │
│ ---                             ┆ ---   ┆ ---        ┆ --- │
│ list[i64]                       ┆ u32   ┆ f64        ┆ u32 │
╞═════════════════════════════════╪═══════╪════════════╪═════╡
│ [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,… ┆ 70    ┆ 0.1595     ┆ 439 │
│ [0, 0, 0, 0, 0, 0, 0, 0, 0, 1,… ┆ 9     ┆ 0.0205     ┆ 439 │
│ [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,… ┆ 8     ┆ 0.0182     ┆ 439 │
│ [0, 0, 0, 0, 0, 0, 0, 1, 0, 0,… ┆ 7     ┆ 0.0159     ┆ 439 │
│ [0, 0, 1, 0, 0, 0, 0, 0, 0, 0,… ┆ 7     ┆ 0.0159     ┆ 439 │
│ [0, 0, 0, 0, 0, 0, 1, 0, 0, 0,… ┆ 7     ┆ 0.0159     ┆ 439 │
│ [0, 1, 0, 0, 0, 0, 0, 0, 0, 0,… ┆ 6     ┆ 0.0137     ┆ 439 │
│ [0, 0, 0, 0, 1, 0, 0, 0, 0, 0,… ┆ 5     ┆ 0.0114     ┆ 439 │
│ [0, 0, 0, 0, 0, 1, 0, 0, 0, 0,… ┆ 5     ┆ 0.0114     ┆ 439 │
│ [0, 0, 0, 0, 0, 0, 0, 0, 1, 0,… ┆ 5     ┆ 0.0114     ┆ 439 │
│ …                               ┆ …     ┆ …          ┆ …   │
│ [0, 0, 0, 1, 0, 1, 1, 0, 1, 1,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [0, 0, 1, 0, 1, 1, 0, 1, 1, 0,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [0, 1, 0, 1, 1, 0, 1, 1, 0, 1,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [1, 1, 0, 1, 0, 1, 1, 1, 0, 0,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [1, 0, 1, 0, 1, 1, 1, 0, 0, 1,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [0, 1, 0, 0, 0, 1, 1, 0, 0, 0,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [1, 0, 0, 0, 1, 1, 0, 0, 0, 0,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [1, 0, 0, 0, 0, 1, 1, 0, 0, 0,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [1, 1, 0, 1, 1, 0, 1, 1, 0, 1,… ┆ 1     ┆ 0.0023     ┆ 439 │
│ [0, 1, 0, 1, 0, 0, 0, 1, 0, 0,… ┆ 1     ┆ 0.0023     ┆ 439 │
└─────────────────────────────────┴───────┴────────────┴─────┘